import { MS_PER_SECOND } from "@/lib/time/time.constants";

export const PRODUCT_STALE_TIME_MS = 2 * 60 * 1000;
export const ORDERS_STALE_TIME_MS = 2 * 60 * 1000;
export const PRODUCT_GC_TIME_MS = 10 * 60 * 1000;
export const FILTER_METADATA_STALE_TIME_MS = 6 * 60 * 60 * 1000;
export const FILTER_METADATA_GC_TIME_MS = 12 * 60 * 60 * 1000;
export const PRODUCT_REVALIDATE_SECONDS = PRODUCT_STALE_TIME_MS / MS_PER_SECOND;
export const FILTER_METADATA_REVALIDATE_SECONDS =
  FILTER_METADATA_STALE_TIME_MS / MS_PER_SECOND;
