import {
  Award,
  Book,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Droplet,
  Eye,
  EyeOff,
  Flame,
  FlameKindling,
  Gift,
  Grid3x3,
  Heart,
  Image,
  LayoutGrid,
  Link2,
  List,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  Search,
  ShieldCheck,
  Truck,
  User,
  Wallet,
} from "lucide-react";

export const iconMap = {
  eye: Eye,
  eyeClose: EyeOff,
  mail: Mail,
  lock: Lock,
  user: User,
  search: Search,
  wallet: Wallet,
  layoutGrid: LayoutGrid,
  gift: Gift,
  flame: Flame,
  droplet: Droplet,
  flameKindling: FlameKindling,
  link2: Link2,
  image: Image,
  book: Book,
  grid: Grid3x3,
  list: List,
  heart: Heart,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  truck: Truck,
  shieldCheck: ShieldCheck,
  award: Award,
  messageCircle: MessageCircle,
  mapPin: MapPin,
  phone: Phone,
} as const;

export type IconName = keyof typeof iconMap;
