export const SCROLL_REVEAL_DURATION_SECONDS = 0.5;
export const SCROLL_REVEAL_DISTANCE_PX = 30;
export const SCROLL_REVEAL_VIEWPORT_AMOUNT = 0.2;
export const SCROLL_REVEAL_EASE = [0.21, 0.47, 0.32, 0.98] as const;
export const STAGGER_REVEAL_CHILDREN_INTERVAL_SECONDS = 0.1;
export const STAGGER_ITEM_SPRING_STIFFNESS = 300;
export const STAGGER_ITEM_SPRING_DAMPING = 24;
